# Generated by Django 5.0.3 on 2026-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lostitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('date_returned', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
