# Generated by Django 4.2.29 on 2026-03-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_returneditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returneditem',
            old_name='owner_name',
            new_name='finder_name',
        ),
    ]
