# Generated by Django 4.2.29 on 2026-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_owner_name_returneditem_finder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returneditem',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
