# Generated by Django 5.0.3 on 2026-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_returneditem_description_returneditem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returneditem',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
