# Generated by Django 5.0.3 on 2026-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_returneditem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='status',
            field=models.CharField(default='Returned', max_length=20),
        ),
    ]
